anti_mal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('campaigns.urls')),
    path('cases/', include('cases.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

cases/urls.py
from django.urls import path
from . import views


app_name = 'cases'
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.add_case, name='new_case')
]

cases/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings


class Case(models.Model):
    AFFECTED_PERSONS_CHOICES = (
        ('children_under_5', 'Children Under 5 years'),
        ('children_under_18', 'Children Under 18 years'),
        ('adults_under_40', 'Adults Under 40 years'),
        ('adults_over_40', 'Children Over 40 years'),
    )

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email_address = models.EmailField(max_length=255, unique_for_date="published")
    mobile_number = models.CharField(max_length=10)
    affected_county = models.CharField(max_length=10)
    affected_persons = models.CharField(max_length=255, choices=AFFECTED_PERSONS_CHOICES)
    case_description = models.TextField(max_length=500, unique=True)
    supportive_image = models.ImageField(upload_to='cases_images')

    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.affected_county

cases/forms.py
from django import forms
from .models import Case


class AlertForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = ('first_name', 'last_name', 'email_address', 'mobile_number', 'affected_county', 'affected_persons',
                  'case_description', 'supportive_image')

    def clean_mobile_number(self):

        data = self.cleaned_data['mobile_number']
        if '@' in data or '-' in data or '|' in data or ' ' in data:
            raise forms.ValidationError("Mobile number cannot have special characters.")
        if 'a' in data or 'b' in data or 'c' in data or 'd' in data or 'e' in data or 'f' in data or 'g' in data:
            raise forms.ValidationError("Mobile number must only contain integers")
        if 'h' in data or 'i' in data or 'j' in data or 'k' in data or 'l' in data or 'm' in data or 'n' in data:
            raise forms.ValidationError("Mobile number must only contain integers")
        if 'o' in data or 'p' in data or 'q' in data or 'r' in data or 's' in data or 't' in data or 'u' in data:
            raise forms.ValidationError("Mobile number must only contain integers")
        if 'v' in data or 'w' in data or 'x' in data or 'y' in data or 'z' in data:
            raise forms.ValidationError("Mobile number must only contain integers")

        return data

cases/views.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render, HttpResponseRedirect
from .forms import AlertForm
from .models import Case


def index(request):
    template = "cases/index.html"
    title = "Reported Malnutrition Cases"
    recent_cases = Case.objects.all().order_by('-published')[0:3]

    context = {
        'template': template,
        'title': title,
        'recent_cases': recent_cases,
    }
    return render(request, template, context)


def add_case(request):
    template = "cases/add_case.html"
    title = "Malnutrition Alerts"
    recent_cases = Case.objects.all().order_by('-published')[0:3]

    if request.method == 'POST':
        form = AlertForm(request.POST, request.FILES)

        if form.is_valid():
            save_case = form.save(commit=False)
            save_case.save()

            #Email sending
            subject = "Thank you for Reporting a Malnutrition Case"
            message = "Your malnutrition alert has been received and we are following up on the issue, you will be contacted within 48 hours for further clarification."
            from_email = settings.EMAIL_HOST_USER
            to_list = [save_case.email_address]

            send_mail(subject, message, from_email, to_list, fail_silently=False)

            subject2 = "Malnutrition Alert"
            message2 = "A malnutrition case has been reported, please check as soon as you can"
            from_email2 = settings.EMAIL_HOST_USER
            to_list2 = [settings.EMAIL_HOST_USER]

            send_mail(subject2, message2, from_email2, to_list2, fail_silently=False)

            messages.success(request, 'Your case was successfully submitted, '
                                      'please note that you may be contacted for more information.')
            return HttpResponseRedirect('new')

    else:
        form = AlertForm

    context = {
        'template': template,
        'title': title,
        'form': form,
        'recent_cases': recent_cases,
    }
    return render(request, template, context)

cases/templates/cases/add_case.html
{% extends 'campaigns/base_layout.html' %}

{% block title %}New Case{% endblock %}

{% block content %}
<div class="row">
    <div class="container">
        <div class="row">
            {% if messages %}
            <ul class="messages card-panel green darken-1 white-text center">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
        <div class="row">


            <div class="col s6 vertical-wrapper">

               <div class="valign" style="text-align: left;">

                   <div class="">
                       <h1 style="font-weight: bolder; text-align: right;"><span class="blue-text text-darken-4">Send an Alert</span><br><span>Save a life</span></h1>
                   </div>

               </div>

            </div>

            <div class="col s6 vertical-wrapper">
               <div class="valign alert-form">

                   <form action="" method="POST" enctype="multipart/form-data" class="card-panel">
                       {% csrf_token %}
                       <h5 class="">Send an Alert</h5>
                       {{ form.as_p }}

                       <input type="submit" value="Submit" class="btn btn-small light-blue darken-4">
                   </form>

               </div>
            </div>


        </div>
    </div>
</div>
{% endblock %}

cases/templates/cases/index.html
{% extends 'campaigns/base_layout.html' %}

{% block title %}Malnutrition cases reported{% endblock %}

{% block content %}
<div class="row">
    <div class="container">
        <div class="row">

            <div class="col s5">
                <div class="">
                    <h4>{{ title }}</h4>
                    <div class="divider"></div>
                    <p style="font-size: 18px;">Have you spotted any malnutrition case, take a step now <br>and report the case so that we can follow up.</p>
                    <h5 class="">Take an action now!!</h5>
                    <p style="font-size: 18px; font-weight: bold;">
                        Send us an alert now.

                        {% if user.is_authenticated%}
                        <a id="scale-demo" href="{% url 'cases:new_case' %}" class="btn-floating btn-large scale-transition
                        light-blue darken-2 hoverable">
                            <i class="material-icons">add</i>
                        </a>
                        {% else %}
                        <p>Login to submit alert <a href="{% url 'login' %}" class="btn btn-small light-blue darken-4">Login</a></p>
                        {% endif %}



                    </p>



                </div>
            </div>
            <div class="col s7 vertical-wrapper">

               <div class="valign" style="text-align: right;">

                   <div class="">
                       <h4>Latest Alerts</h4>

                        {% if recent_cases %}
                            {% for rc in recent_cases %}
                               <div class="row hoverable" style="border: 1px solid lavender; padding: 10px;">
                                   <div class="col s5">
                                       <img src="{{ rc.supportive_image.url }}" alt="Campaign" width="250px" height="auto">
                                   </div>
                                   <div class="col s7">
                                       <h6><b>County</b></h6>
                                       <p>{{ rc.affected_county }}</p>
                                        <h6><b>Affected persons</b></h6>
                                       <p>{{ rc.affected_persons }}</p>
                                   </div>
                               </div>

                           {% endfor %}
                        {% else %}
                            <div class="card-panel">
                                 <p class="red-text" style="font-size: 20px;">No alerts available at the moment</p>
                            </div>

                        {% endif %}


                   </div>

               </div>

            </div>

        </div>
    </div>
</div>
{% endblock %}