accounts/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from . import views as core_views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    #path('', include('django.contrib.auth.urls')),
    #path('signup/', views.SignUp.as_view(), name='signup'),
    path('signup/', views.register, name='signup'),
    path('<int:user_id>/profile/', views.user_profile_view, name='profile'),
    path('<int:user_id>/profile/edit/', views.edit_profile_view, name='edit_profile'),

    #path('account_activation_sent/', core_views.account_activation_sent, name='account_activation_sent'),
    #path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', core_views.activate, name='activate'),

    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),
]

anti_mal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('campaigns.urls')),
    path('cases/', include('cases.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

campaigns/urls.py
from django.urls import path
from . import views


app_name = 'campaigns'
urlpatterns = [
    path('', views.index, name='index'),
    path('posted_campaigns', views.posted_campaigns, name='posted_campaigns'),
    path('<int:campaign_id>', views.details, name='details'),
    path('<int:campaign_id>/vote', views.vote, name='vote'),
    path('<int:open_campaign_id>/add_campaign', views.add_campaign, name='add_campaign'),
    # path('<int:id>/results', views.results, name='results'),
]

cases/urls.py
from django.urls import path
from . import views


app_name = 'cases'
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.add_case, name='new_case')
]

campaigns/models.py
from django.db import models
from django.utils import timezone
from datetime import date
from django.conf import settings
from django.core import validators
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User


class County(models.Model):
    county_name = models.CharField(max_length=100)
    county_code = models.CharField(max_length=100)

    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.county_name


class OpenCampaign(models.Model):

    CAMPAIGN_STATUS_CHOICES = (
        ('open', 'Open'),
        ('closed', 'Closed')
    )

    campaign_title = models.CharField(max_length=250)
    region = models.ForeignKey(County, on_delete=models.CASCADE)
    target_population = models.CharField(max_length=250)
    running_from = models.DateField()
    running_to = models.DateField()
    thumbnail = models.ImageField(upload_to='open_campaigns')

    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    registration_status = models.CharField(max_length=250, choices=CAMPAIGN_STATUS_CHOICES, default='Open')
    voting_status = models.CharField(max_length=250, choices=CAMPAIGN_STATUS_CHOICES, default='Open')

    # Restring end date(should not be less than start date)
    def clean(self):
        start_date = self.running_from
        end_date = self.running_to
        if end_date < start_date:
            raise ValidationError({'running_to': ["Invalid end date, cannot be before start date"]})

    # Restring start date(should not be less than today's date)
        if start_date < date.today():
            raise ValidationError({'running_from': ["Invalid start date, cannot be a date before today's date"]})

    def __str__(self):
        return self.campaign_title


class SubmittedCampaign(models.Model):

    CAMPAIGN_STATUS = (
        ('won', 'Won'),
        ('lost', 'Lost'),
        ('waiting', 'Waiting')
    )

    APPLICANT_TYPE_CHOICES = (
        ('group', 'Group'),
        ('organization', 'Organization')
    )

    open_campaign = models.ForeignKey(OpenCampaign, on_delete=models.CASCADE)
    applicant_type = models.CharField(max_length=100, choices=APPLICANT_TYPE_CHOICES)
    organization_or_group_name = models.CharField(max_length=100)
    email_address = models.EmailField(max_length=255)
    mobile_number = models.CharField(max_length=10)
    county = models.ForeignKey(County, on_delete=models.CASCADE)
    city = models.CharField(max_length=255)

    group_or_org_description = models.TextField(max_length=1000, help_text='Briefly describe your group/organization')
    supporting_image = models.ImageField(upload_to='campaign_images')
    group_or_org_profile = models.FileField(upload_to='campaign_profiles', help_text='Upload a pdf of your profile')
    status = models.CharField(max_length=255, choices=CAMPAIGN_STATUS, default='waiting')

    # user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    total_votes = models.IntegerField(default=0, blank=True, null=True)

    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.organization_or_group_name

    class Meta:
        verbose_name_plural = 'Submitted Campaigns'


class Vote(models.Model):
    open_campaign = models.CharField(max_length=250)
    organization_or_group_name = models.CharField(max_length=255)
    voter_name = models.CharField(max_length=250)
    voter_id = models.IntegerField()
    vote_time = models.CharField(max_length=250, default='')

    def __str__(self):
        return self.voter_name

    class Meta:
        verbose_name_plural = "Votes"

campaigns/forms.py
from django import forms
from .models import Vote, SubmittedCampaign
from django.contrib.auth.models import User


class VoterForm(forms.ModelForm):
    class Meta:
        model = Vote
        fields = ('open_campaign', 'organization_or_group_name', 'voter_name', 'voter_id', 'vote_time')


class CampaignForm(forms.ModelForm):
    class Meta:
        model = SubmittedCampaign
        fields = ('open_campaign', 'applicant_type',
                  'organization_or_group_name', 'email_address', 'mobile_number', 'county', 'city',
                  'group_or_org_description', 'supporting_image', 'group_or_org_profile')

    def clean_mobile_number(self):

        data = self.cleaned_data['mobile_number']
        if '@' in data or '-' in data or '|' in data or ' ' in data or '_' in data:
            raise forms.ValidationError("Mobile number cannot have special characters.")
        if 'a' in data or 'b' in data or 'c' in data or 'd' in data or 'e' in data or 'f' in data or 'g' in data:
            raise forms.ValidationError("Mobile number must only contain integers")
        if 'h' in data or 'i' in data or 'j' in data or 'k' in data or 'l' in data or 'm' in data or 'n' in data:
            raise forms.ValidationError("Mobile number must only contain integers")
        if 'o' in data or 'p' in data or 'q' in data or 'r' in data or 's' in data or 't' in data or 'u' in data:
            raise forms.ValidationError("Mobile number must only contain integers")
        if 'v' in data or 'w' in data or 'x' in data or 'y' in data or 'z' in data:
            raise forms.ValidationError("Mobile number must only contain integers")

        return data

    def clean_email_address(self):
        data = self.cleaned_data['email_address']
        if data != User.email:
            raise forms.ValidationError("Email address doesn't match your account email.")

campaigns/views.py
from django.shortcuts import render, HttpResponse
from .models import SubmittedCampaign, County, Vote, OpenCampaign
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from .forms import VoterForm, CampaignForm
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail


def index(request):
    title = 'Open Campaigns'
    template = 'campaigns/index.html'
    campaigns = OpenCampaign.objects.filter(registration_status='open')

    context = {
        'title': title,
        'campaigns': campaigns,
    }

    return render(request, template, context)


def posted_campaigns(request):
    title = 'Proposed Campaigns'
    template = 'campaigns/campaigns.html'
    campaigns = SubmittedCampaign.objects.all().order_by('-published')
    voting = OpenCampaign.objects.filter(voting_status='open')

    #open_camapaign_title = OpenCampaign.campaign_title

    context = {
        'title': title,
        'campaigns': campaigns,
        'voting': voting,
    }

    return render(request, template, context)


def details(request, campaign_id):
    campaign = SubmittedCampaign.objects.get(id=campaign_id)
    context = {
        'campaign': campaign,
    }
    return render(request, 'campaigns/details.html', context)


def vote(request, campaign_id):
    campaign = SubmittedCampaign.objects.get(id=campaign_id)
    #open_campaign = SubmittedCampaign.open_campaign_id
    #voting_status = open_campaign
    title = "Confirm your vote"
    template = 'campaigns/vote.html'
    date = timezone.now
    current_user = request.user

    if request.method == 'POST':
        form = VoterForm(request.POST)

        if form.is_valid():
            user = Vote.objects.filter(voter_id=current_user.id)
            if user:
                messages.warning(request, 'You can only vote once.')
                return HttpResponseRedirect('vote')
            else:
                form.save()

                campaign = get_object_or_404(SubmittedCampaign, pk=campaign_id)

                campaign.total_votes += 1
                campaign.save()

                messages.success(request, 'Your vote was successfully submitted.')
                return HttpResponseRedirect('../')

    else:

        form = VoterForm

    context = {
        'form': form,
        'title': title,
        'campaign': campaign,
        'date': date,
        'current_user': current_user,
        #'voting_status': voting_status,
    }

    return render(request, template, context)

    # campaign = get_object_or_404(Campaign, pk=campaign_id)

    # campaign.total_votes += 1
    # campaign.save()

    # return HttpResponseRedirect(reverse('campaigns:details', args=(campaign.id,)))
    # return HttpResponse("Voting for campaign with an ID of %s" % campaign_id)


def add_campaign(request, open_campaign_id):
    campaign = OpenCampaign.objects.get(id=open_campaign_id)
    open_campaigns = OpenCampaign.objects.all()
    title = 'Submit your campaign'
    template = 'campaigns/add_campaign.html'
    date = timezone.now

    if request.method == 'POST':
        form = CampaignForm(request.POST, request.FILES)

        if form.is_valid():
            campaign_save = form.save(commit=False)
            campaign_save.save()

            # Email sending
            subject = "Campaign Proposal Submitted"
            message = "Your campaign proposal has been received and is awaiting the voting period."
            from_email = settings.EMAIL_HOST_USER
            to_list = [campaign_save.email_address]

            send_mail(subject, message, from_email, to_list, fail_silently=False)

            subject2 = "New Campaign Proposal"
            message2 = "A new campaign proposal has been submitted to your system"
            from_email2 = settings.EMAIL_HOST_USER
            to_list2 = [settings.EMAIL_HOST_USER]

            send_mail(subject2, message2, from_email2, to_list2, fail_silently=False)

            messages.success(request, "Your campaign has been received, wait for the voting period")
            return HttpResponseRedirect('../')
        else:
            messages.error(request, "Invalid data! Please correct the errors below")
    else:
        form = CampaignForm

    context = {
        'campaign': campaign,
        'open_campaigns': open_campaigns,
        'title': title,
        'date': date,
        'form': form,
    }
    return render(request, template, context)

    #return HttpResponse('Add new campaigns page')

campaigns/templates/campaigns/add_campaign.html
{% extends 'campaigns/base_layout.html' %}

{% block title %}New Campaign{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <h5>{{ title }}</h5>
    </div>
    <div class="">
        {% if messages %}
        <ul class="messages card-panel red darken-1 white-text center">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div class="row card-panel hoverable">

        <div class="row">

            <!--<form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="col s5 vertical-wrapper">
                    <input type="text" value="{{ campaign.id }}" name="open_campaign_id" hidden>

                    <input type="text" name="campaign_owner_id" value="{% if user.is_authenticated %}{{ user.id }}{% endif %}" hidden>

                    <div class="input-field">
                        <select typeof="select" name="open_campaign" required>
                            <option value="" disabled selected>Choose a campaign</option>
                            {% for open_campaign in open_campaigns %}

                            <option value="{{ open_campaign.campaign_title }}">{{ open_campaign.campaign_title }}</option>

                            {% endfor %}
                        </select>
                        &lt;!&ndash;<label>Open Campaign</label>&ndash;&gt;
                    </div>

                    <div class="input-field">
                        <select typeof="select" name="applicant_type" id="" required>
                            <option value="" disabled selected>Choose applicant type</option>
                            <option value="group">Group</option>
                            <option value="organization">Organization</option>
                        </select>
                        &lt;!&ndash;<label>Applicant type</label>&ndash;&gt;
                    </div>
                    <div class="input-field">
                        <label>Organization/Group Name</label>
                        <input type="text" name="organization_or_group_name" required>
                    </div>
                    <div class="input-field">
                        <label>Group/Organization Email</label>
                        <input type="text" name="email_address" required>
                    </div>
                    <div class="input-field">
                        <label>Group/Organization Mobile Number</label>
                        <input type="text" name="mobile_number" required>
                    </div>

                </div>
                <div class="col s7 vertical-wrapper">
                    <div class="row">
                        <div class="col s6">
                            <div class="input-field">
                                <label>County</label>
                                <input type="text" name="county" required>
                            </div>
                        </div>
                        <div class="col s6">
                            <div class="input-field">
                                <label>City</label>
                                <input type="text" name="city" required>
                            </div>
                        </div>
                    </div>
                    <div class="input-field">
                        <label>Group/Org Brief Description</label>
                        <textarea name="group_or_org_description"
                                  style="width: 100%; min-width: 100%; max-width: 100%; height: 150px;
                                  min-height: 150px; max-height: 150px;" required></textarea>
                    </div>
                    <div class="">
                        <label>Supporting Image</label>
                        <div class="">
                            <input type="file" name="supporting_image" required>
                        </div>
                    </div>

                    <br><br>
                    <input type="submit" value="Submit" class="btn btn-small light-blue darken-4 right">
                </div>


            </form>-->

            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {{ form.as_p }}
                <br><br>
                <input type="submit" value="Submit" class="btn btn-small light-blue darken-4 right">

            </form>

        </div>
    </div>
</div>
{% endblock %}

campaigns/templates/campaigns/base_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <title>{% block title %}Anti-mal{% endblock %}</title>

    {% load static %}
    <!--Import Google Icon Font for materialize.css-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' media='screen,projection' %}"  media="screen,projection"/>
   <!--Bootstrap css-->
    <!--<link type="text/css" rel="stylesheet" href="{% static 'bootstrap\css\bootstrap.min.css' %}">-->
    <!--Custom CSS-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/home.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/campaigns_index.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/cases.css' %}">

</head>
<body>
    <div class="row">
        <header>
            <div class="">
                <nav class="light-blue darken-4">
                    <ul class="right hide-on-med-and-down">
                        {% if user.is_authenticated %}
                        <li><i><small><a href="{% url 'accounts:profile' user.id  %}">{{ user.username }}</a></small></i></li>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                        {% endif %}
                      </ul>
                    <div class="nav-wrapper container">
                      <a href="#!" class="brand-logo">Nutritious Kenya</a>
                      <a href="#" data-target="mobile-nav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                      <ul class="right hide-on-med-and-down">
                        <li><a href="{% url 'campaigns:index' %}">Home</a></li>
                        <li><a href="{% url 'campaigns:posted_campaigns' %}">Campaigns</a></li>
                        <li><a href="{% url 'cases:index' %}">Alerts</a></li>
                        <li><a href="">Contributions</a></li>
                      </ul>
                    </div>
                </nav>

                <!--Mobile Materialize css navbar with menu-->
                  <ul class="sidenav" id="mobile-nav">
                      <li><a href="#">Home</a></li>
                      <li><a href="#">Campaigns</a></li>
                      <li><a href="#">Contributions</a></li>
                      <ul class="right">
                        {% if user.is_authenticated %}
                        <li><i><small>{{ user.username }}</small></i></li>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                        {% endif %}
                      </ul>
                  </ul>
            </div>
        </header>
    </div>
    <div class="row main-content-section">
        <main>
            {% block content %}
                <p>Main contect section</p>
            {% endblock %}
        </main>
    </div>
    <div class="row">
        <footer>
            <div class="container">
                <div class="divider"></div>
                <div class="col l6 s12 vertical-wrapper footer-links">
                    <div class="valign">
                        <ul>
                            <li><a href="">Terms of Use</a></li>
                            <li><a href="">Privacy Policy</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col l6 s12 vertical-wrapper copyright">
                    <div class="valign">
                        <p class="right">Copyright &copy;2019. | All rights reserved | A product of B.M.M</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>


    <!--JQuery-->
    <script type="text/javascript" src="{% static 'js/jquery/jquery.min.js' %}"></script>
    <!--Bootstrap js-->
    <!--<script type="text/javascript"src="{% static 'bootstrap\js\bootstrap.min.js' %}"></script>-->
    <!--Materialize js-->
    <script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script>

    <!--Custom JS-->
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>

campaigns/templates/campaigns/campaigns.html
{% extends 'campaigns/base_layout.html' %}

{% block title %}Posted Campaigns{% endblock %}

{% block content %}
    <div class="campaigns-main">
        <div class="container">


            {% if messages %}
            <ul class="messages card-panel green darken-1 white-text center">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}

            <div class="col s12">
                <div class="divider"></div>
                <div class="" style="background-color: lavender; padding: 10px 4px;">
                    <a id="scale-demo" href="{% url 'campaigns:index' %}" class="btn-floating scale-transition light-blue darken-2 right">
                        <i class="material-icons">add</i>
                    </a>
                    <h5 style="text-transform: uppercase; font-weight: bold;">{{ title }}</h5>
                </div>
                <div class="divider"></div>

                {% if campaigns %}
                        {% for campaign in campaigns %}
                        <div class="card-wrapper">
                          <div class="card col l4 s12 vertical-wrapper card-panel">
                            <div class="card-image waves-effect waves-block waves-light">
                              <img class="activator" src="{{ campaign.supporting_image.url }}">
                            </div>
                            <div class="card-content">
                              <span class="card-title activator grey-text text-darken-4">
                                  <a href="{% url 'campaigns:details' campaign.id %}" class="campaign-title">{{ campaign.organization_or_group_name }}</a>
                                  <i class="material-icons right">more_vert</i>
                              </span>
                              <!--<p><a href="#">Vote</a></p>-->
                            </div>
                            <div class="card-reveal">
                              <span class="card-title grey-text text-darken-4">
                                  <i class="material-icons right">close</i>
                                  <a href="{% url 'campaigns:details' campaign.id %}" class="campaign-title black-color">{{ campaign.organization_or_group_name }}</a>
                              </span>

                              <!--<p class="start-date"><b>From: </b> {{ campaign.start_date }}</p>
                              <p class="end-date"><b>To: </b>{{ campaign.end_date }}</p>
                                <p><b>Region:</b>{{ campaign.target_region }}</p>-->
                              <!--<p>{{ campaign.brief_description|slice:":120" }} ...</p>-->
                              <a href="{% url 'campaigns:details' campaign.id %}" class="btn btn-small light-blue darken-4 right">View</a>
                              <div class="">
                                {% if user.is_authenticated %}
                                <a href="{% url 'campaigns:vote' campaign.id %}" class="btn btn-small light-blue darken-4">Vote</a>
                                <!--<p class="votes right"><b>Votes: </b>{{ campaign.total_votes }}</p>-->
                                {% else %}
                                <a href="{% url 'login' %}" class="btn btn-small light-blue darken-4"> Login to Vote</a>
                                <a href="{% url 'accounts:signup' %}" class="btn btn-small light-blue darken-1 right">New Voter</a>
                                {% endif %}
                              </div>
                            </div>
                          </div>


                      </div>
                    {% endfor %}
                {% else %}
                    <div class="card-panel red-text">
                        <p>There are no campaigns at the moment!</p>
                    </div>
                {% endif%}


            </div>
        </div>
    </div>
{% endblock %}

campaigns/templates/campaigns/details.html
{% extends 'campaigns/base_layout.html' %}

{% block title %}Campaign{% endblock %}

{% block content %}
<div class="container">
    <div class="row card">
        <div class="col l7 s12 vertical-wrapper vote-sec1">
            <h5><b>{{ campaign.open_campaign}}</b></h5>
            <div class="divider"></div>
            <h6><b>Group/Org Name:</b> {{ campaign.organization_or_group_name }}</h6>
            <div class="divider"></div>
            <h6><b>Description</b></h6>
            <p>{{ campaign.group_or_org_description }}</p>
            <div class="divider"></div>
        </div>
        <div class="col l5 s12 vertical-wrapper vote-sec2">
            <img src="{{ campaign.supporting_image.url }}" alt=""width="100%" height="auto">

            <div class="">
                {% if user.is_authenticated %}
                <a href="{% url 'campaigns:vote' campaign.id %}" class="btn btn-small light-blue darken-4">Vote</a>
                <!--<p class="votes right"><b>Votes: </b>{{ campaign.total_votes }}</p>-->
                {% else %}
                <a href="{% url 'login' %}" class="btn btn-small light-blue darken-4"> Login to Vote</a>
                <a href="{% url 'accounts:signup' %}" class="btn btn-small light-blue darken-1 right">New Voter</a>
                {% endif %}
            </div>

        </div>
    </div>
</div>
{% endblock %}

campaigns/templates/campaigns/vote.html
{% extends 'campaigns/base_layout.html' %}

{% block title %}Vote{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <h4>{{ title }}</h4>
    </div>
    <div class="">
        {% if messages %}
        <ul class="messages card-panel red darken-1 white-text center">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div class="row card-panel hoverable">


        <div class="row">
            <form action="" method="POST">
                {% csrf_token %}
                <!--{{ form.as_p }}-->

                <div class="row">
                    <div class="col l7 s12 vertical-wrapper vote-sec1">

                        <div class="row">
                            <div class="col l8 s12 vertical-wrapper">
                                <label>Voter's name</label>
                                <input type="text" name="voter_name" value="{% if user.is_authenticated %}{{ user.username }}{% endif %}
                                " readonly>
                            </div>
                            <div class="col l4 s12 vertical-wrapper">
                                <label>Voter's ID</label>
                                <input type="text" name="voter_id" value="{% if user.is_authenticated %}{{ user.id }}{% endif %}" readonly>
                            </div>
                        </div>

                        <label>Campaign Applied</label>
                        <input type="text" name="open_campaign" value="{{ campaign.open_campaign}}" readonly>
                        <label>Applicant name</label>
                        <input type="text" name="organization_or_group_name" value="{{ campaign.organization_or_group_name }}" readonly>

                    </div>
                    <div class="col l5 s12 vertical-wrapper vote-sec2">
                        <img src="{{ campaign.supporting_image.url }}" alt=""width="100%" height="auto">
                        <label>Date</label>
                        <input type="text" name="vote_time" value="{{ date }}" readonly>
                    </div>
                </div>

                <input type="submit" value="Submit Vote" class="btn btn-small light-blue darken-4">
                <a href="{% url 'campaigns:details' campaign.id %}" class="btn btn-small light-blue">Cancel</a>
                <a href="{% url 'campaigns:index' %}" class="btn btn-small light-blue darken-2">Change Campaign</a>

            </form>
            <!--<form action="{% url 'campaigns:vote' campaign.id %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}

                <input type="submit" value="Vote" class="btn btn-small light-blue darken-4">

            </form>-->
        </div>


    </div>
</div>
{% endblock %}