accounts/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from . import views as core_views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    #path('', include('django.contrib.auth.urls')),
    #path('signup/', views.SignUp.as_view(), name='signup'),
    path('signup/', views.register, name='signup'),
    path('<int:user_id>/profile/', views.user_profile_view, name='profile'),
    path('<int:user_id>/profile/edit/', views.edit_profile_view, name='edit_profile'),

    #path('account_activation_sent/', core_views.account_activation_sent, name='account_activation_sent'),
    #path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', core_views.activate, name='activate'),

    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),
]

anti_mal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('campaigns.urls')),
    path('cases/', include('cases.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

campaigns/urls.py
from django.urls import path
from . import views


app_name = 'campaigns'
urlpatterns = [
    path('', views.index, name='index'),
    path('posted_campaigns', views.posted_campaigns, name='posted_campaigns'),
    path('<int:campaign_id>', views.details, name='details'),
    path('<int:campaign_id>/vote', views.vote, name='vote'),
    path('<int:open_campaign_id>/add_campaign', views.add_campaign, name='add_campaign'),
    # path('<int:id>/results', views.results, name='results'),
]

cases/urls.py
from django.urls import path
from . import views


app_name = 'cases'
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.add_case, name='new_case')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)
    # other fields...


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
#from .models import UserProfile


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password')


#class EditProfileForm2(forms.ModelForm):
 #   class Meta:
  #      model = UserProfile
   #     fields = ('description', 'city', 'website', 'phone', 'profile')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import UserRegistrationForm
from campaigns.models import SubmittedCampaign, Vote
# from accounts.models import ProfilePictures
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import login, authenticate

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from .tokens import account_activation_token

from django.contrib.auth import login
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode




#def register(request):
 #   if request.method == 'POST':
  #      form = UserRegistrationForm(request.POST)
   #     if form.is_valid():
    #        form.save()
     #       username = form.cleaned_data.get('username')
      #      raw_password = form.cleaned_data.get('password1')
       #     user = authenticate(username=username, password=raw_password)
        #    login(request, user)

         #   messages.success(request, 'Your account has been created successfully')
          #  return render(request, 'accounts/register_done.html')
    #else:
     #   form = UserRegistrationForm()
    #return render(request, 'accounts/signup.html', {'form': form})


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your Nutritious Kenya Account'
            message = render_to_string('accounts/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return redirect('accounts:account_activation_sent')
    else:
        form = UserRegistrationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def account_activation_sent(request):
    template = 'accounts/account_activation_sent.html'

    return render(request, template)


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        messages.success(request, 'You account has been successfully activated, you can now login, upload campaign proposals and report malnutrition cases.')
        return redirect('/')
    else:
        return render(request, 'accounts/account_activation_invalid.html')


def user_profile_view(request, user_id):
    #user_details = User.objects.get(id=user_id)
    user_details = request.user
    #campaigns = Campaign.objects.filter(campaign_owner_id=user_id)
    #campaigns = SubmittedCampaign.objects.filter(campaign_owner_id=request.user.id)
    user = request.user.id
    votes = Vote.objects.filter(voter_id=user)

    #profile = ProfilePictures.objects.all()

    title = 'Dashboard'
    template = 'accounts/profile.html'

    #if request.method == 'POST':
     #   form = forms.ProfilePictureForm(request.POST, request.FILES)

      #  if form.is_valid():
       #     form.save()

        #else:
         #   messages.error(request, "Cannot update profile image")
    #else:
     #   form = forms.ProfilePictureForm

    context = {
        'user_details': user_details,
        'title': title,
        #'campaigns': campaigns,
        'votes': votes,
        #'form': form,
        # 'profile': profile,
    }
    return render(request, template, context)


def edit_profile_view(request, user_id):
    template = 'accounts/edit_profile.html'
    title = 'Edit Profile'

    if request.method == 'POST':
        form = forms.EditProfileForm(request.POST, instance=request.user)
        #more_details_form = forms.EditProfileForm2(request.POST, instance=request.user, files=request.FILES)
        #if form.is_valid() and more_details_form.is_valid():
        if form.is_valid():
            form.save()
         #   more_details_form.save()

            messages.success(request, "You profile has been successfully updated")
            #return redirect('/accounts/profile')

        else:
            messages.error(request, "Invalid form data")
    else:
        form = forms.EditProfileForm(instance=request.user)
        #more_details_form = forms.EditProfileForm2(instance=request.user)

    context = {
        'template': template,
        'title': title,
        'form': form,
        #'more_details_form': more_details_form
    }

    return render(request, template, context)

accounts/templates/accounts/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to activate your account on nutritious Kenya:
If you did not make the request then report this case.

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/account_activation_invalid.html
{% extends 'campaigns/base_layout.html' %}

{% block title %}Invalid activation link{% endblock %}

{% block content %}
    <div class="row login-main">
        <div class="container">
            <p>Your activation link is invalid or has expired, create your account again.</p>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/account_activation_sent.html
{% extends 'campaigns/base_layout.html' %}

{% block title %}Account activation{% endblock %}

{% block content %}
    <div class="row login-main">
        <div class="container">
            <p>Please check your email address to activate your account.</p>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'campaigns/base_layout.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
    <div class="row login-main">
        <div class="container">
            <div class="row">
                {% if messages %}
                <ul class="messages card-panel green darken-1 white-text center">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            <div class="row">
                <div class="col s5 vertical-wrapper">
                    <h5><b>{{ title }}</b></h5>
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <!--{{ form.as_p }}-->
                        <input type="text" name="first_name" value="{{ user.first_name }}" placeholder="First Name">
                        <input type="text" name="last_name" value="{{ user.last_name }}" placeholder="Last Name">
                        <input type="email" name="email" value="{{ user.email }}" placeholder="Email Address">

                        <!--{{ more_details_form.as_p }}-->
                        <input type="submit" value="Update" class="btn btn-small light-blue darken-4">
                        <a href="{% url 'password_change' %}" class="btn btn-small light-blue darken-3">Change Password</a>
                    </form>
                </div>
                <div class="col s7 vertical-wrapper">

                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'campaigns/base_layout.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
    <div class="row login-main">
        <div class="container">
            <div class="row">
                {% if messages %}
                <ul class="messages card-panel green darken-1 white-text center">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            <div class="row">
                <div class="col l3 s12 vertical-wrapper">
                    <div class="valign">
                        <div class="card-panel">
                            <h5>Dashboard</h5>
                            <ul class="tabs">
                                <li class="tab"><a href="#profile">Profile</a></li>
                                <!--<li class="tab"><a href="#tab2">My Campaigns</a></li>-->
                                <li class="tab"><a href="#tab3">My Votes</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col l9 s12 vertical-wrapper">
                    <div class="valign">
                        <div class="col sm6" id="profile">
                            <h5>Profile</h5>
                            <div class="row">
                                <!--<img src="{{ profile.profile_image.url }}" alt="Profile image"
                                             style="width: 100px; height: auto; border-radius: 99px;">-->
                                <img src="../../../static/media/staticimages/user.png" alt="Profile image"
                                             style="width: 100px; height: auto; border-radius: 99px;">

                                <h6><b>Name: </b>{{ user.first_name }} {{ user.last_name }}</h6>
                                <p><b>Username: </b>{{ user.username }}</p>
                                <p><b>Email: </b>{{ user.email }}</p>

                                <div class="">
                                    <a href="{% url 'accounts:edit_profile' user.id %}" class="btn btn-small light-blue darken-4">Edit profile</a>
                                    <a href="{% url 'password_change' %}" class="btn btn-small light-blue darken-3">Change Password</a>
                                </div>

                            </div>



                        </div>
                        <!--<div class="col s12" id="tab2">
                            <div class="row">
                                <div class="right">
                                    <td><a href="{% url 'campaigns:index' %}" class="btn btn-small light-blue darken-2"><i class="small material-icons">add</i></a></td>
                                </div>
                                <h5>My Campaigns</h5>
                            </div>

                            {% if campaigns %}
                            <div class="row">
                                <table>
                                    &lt;!&ndash;<thead>&ndash;&gt;
                                        <tr>
                                            <th>Campaign applied</th>
                                            <th>Our name</th>
                                            <th>Email</th>
                                            <th>Votes</th>
                                            <th></th>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                    &lt;!&ndash;</thead>&ndash;&gt;
                                {% for campaign in campaigns %}

                                    &lt;!&ndash;<tbody>&ndash;&gt;
                                        <tr>
                                            <td>{{ campaign.open_campaign }}</td>
                                            <td>{{ campaign.organization_or_group_name }}</td>
                                            <td>{{ campaign.email_address }}</td>
                                            <td>{{ campaign.total_votes }}</td>
                                            <td><a href="" class="btn btn-small light-blue darken-4">View</a></td>
                                            <td><a href="" class="btn btn-small light-blue darken-2">Edit</a></td>
                                            <td><a href="" class="btn btn-small red darken-4">Delete</a></td>

                                        </tr>
                                    &lt;!&ndash;</tbody>&ndash;&gt;
                                {% endfor %}

                                </table>

                            </div>
                            {% else %}

                            <div class="red darken-2 white-text">
                                <p style="padding: 30px 15px;">
                                    You have no campaigns at the moment!
                                </p>
                            </div>
                            {% endif %}


                        </div>-->
                        <div class="row" id="tab3">
                            <h5>My Votes</h5>
                            <div class="">

                                {% for vote in votes %}
                                <table class="">
                                    <thead>
                                        <tr>
                                            <th>Campaign</th>
                                            <th>Group/Org Name</th>
                                            <th>Vote Date</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>{{ vote.open_campaign }}</td>
                                            <td>{{ vote.organization_or_group_name }}</td>
                                            <td>{{ vote.vote_time }}</td>
                                            <td><a href="" class="btn btn-small light-blue darken-4">View</a></td>

                                        </tr>
                                    </tbody>
                                    <td>{{ campaign.open_campaign }}</td>
                                </table>
                                {% empty %}
                                <div class="red darken-2 white-text">
                                    <p style="padding: 30px 15px;">
                                        You have not voted for any campaign yet! You can vote now.
                                        <a href="{% url 'campaigns:posted_campaigns' %}" class="btn btn-small light-blue darken-3">Vote</a>
                                    </p>

                                </div>

                                {% endfor %}
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/register_done.html
{% extends 'campaigns/base_layout.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="row login-main">
        <div class="container">
            <div class="row">
                {% if messages %}
                <ul class="messages card-panel green darken-1 white-text center">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            <div class="row">
                <div class="card-panel center">
                    <h6>Welcome to Nutritious Kenya</h6>
                    <p>You can now add campaign proposals and report malnutrition cases</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'campaigns/base_layout.html' %}

{% block title %}SignUp{% endblock %}

{% block content %}
    <div class="row login-main">
        <div class="container">
            <div class="row">
                {% if messages %}
                <ul class="messages card-panel green darken-1 white-text center">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            <div class="row">
                <div class="col l7 s12 vertical-wrapper">
                    <div class="valign">

                    </div>
                </div>
                <div class="col l5 s12 vertical-wrapper">
                    <div class="valign reg-form">
                        <form action="" method="POST" class="card-panel">
                            <h5>Signup</h5>
                            <div class="divider"></div>
                            {% csrf_token %}
                            <!--{{ user_form.as_p }}-->
                            {{ form.as_p }}
                            <input type="submit" value="Signup" class="btn light-blue darken-4">
                            <br><br>
                            <div class="divider"></div>
                            <br>
                            Already have an account?<a href="{% url 'login' %}" class=""> Login</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}